Update 05-azure-kubernetes-cluster-iaac-pipeline.yml for Azure Pipelines

diff --git a/05-azure-kubernetes-cluster-iaac-pipeline.yml b/05-azure-kubernetes-cluster-iaac-pipeline.yml
--- a/05-azure-kubernetes-cluster-iaac-pipeline.yml
+++ b/05-azure-kubernetes-cluster-iaac-pipeline.yml
@@ -14,8 +14,14 @@ steps:
     scriptType: 'bash'
     scriptLocation: 'inlineScript'
     inlineScript: |
+      # Verify the subscription
+      az account show --subscription daae98de-d83f-4119-8b18-233a5a778f4f
+      if [ $? -ne 0 ]; then
+        echo "Subscription not found. Exiting..."
+        exit 1
+      fi
       # Set the correct subscription
-      az account set --subscription "daae98de-d83f-4119-8b18-233a5a778f4f"
+      az account set --subscription daae98de-d83f-4119-8b18-233a5a778f4f
       # Check if storage account exists
       if ! az storage account show --name storageaccountcsamal05882 --resource-group terraform-backend-rg; then
         echo "Storage account does not exist. Creating storage account..."
